apiVersion: v1
kind: Pod
metadata:
  name: "lifecycle-demo"
spec:
  terminationGracePeriodSeconds: 8
  containers:
  - name: lifecycle-demo-container
    image: quay.io/myan/lifecycle:latest
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c", "/bin/poststart.sh > /proc/1/fd/1"]
      preStop:
        exec:
          command: ["sh", "-c", "/bin/prestop.sh > /proc/1/fd/1"]
    volumeMounts:
      - name: hooks
        mountPath: /usr/share/
  volumes:
    - name: hooks
      hostPath:
        path: /usr/hooks/


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-user-clusteradmin
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default  
    namespace: default 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

  